name: Update NOTAM and Deploy to Pages

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "*/15 * * * *" 
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-notam:
    runs-on: ubuntu-latest
    env:
      NOTAM_SMTP_USER: ${{ secrets.NOTAM_SMTP_USER }}
      NOTAM_SMTP_AUTH_CODE: ${{ secrets.NOTAM_SMTP_AUTH_CODE }}
      NOTAM_FROM_EMAIL: ${{ secrets.NOTAM_FROM_EMAIL }}
      NOTAM_TO_EMAILS: ${{ secrets.NOTAM_TO_EMAILS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Echo runner IP
        run: echo "${{ steps.ip.outputs.ipv4 }}"

      - name: Update NOTAM list
        run: |
          python3 main.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto update NOTAM list" || echo "No changes to commit"
          git push

  deploy:
    needs: update-notam
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
